name: Preview deploy on PR

on:
  pull_request:
    # Build & deploy preview on open/update, then clean up on close
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

permissions:
  contents: read
  checks: write

jobs:
  build_and_preview:
    # Only run build/deploy while the PR is open (not on "closed")
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env.local (Vite)
        run: |
          cat > .env.local << 'EOF'
          VITE_FB_API_KEY=${{ secrets.VITE_FB_API_KEY }}
          VITE_FB_AUTH_DOMAIN=${{ secrets.VITE_FB_AUTH_DOMAIN }}
          VITE_FB_PROJECT_ID=${{ secrets.VITE_FB_PROJECT_ID }}
          VITE_FB_STORAGE_BUCKET=${{ secrets.VITE_FB_STORAGE_BUCKET }}
          VITE_FB_SENDER_ID=${{ secrets.VITE_FB_SENDER_ID }}
          VITE_FB_APP_ID=${{ secrets.VITE_FB_APP_ID }}
          EOF

      - name: Build
        run: npm run build

      - name: Deploy preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SARVTEK_NICHE_FINDER }}
          projectId: sarvtek-niche-finder
          channelId: pr-${{ github.event.number }}  # stable channel name per PR
          expires: 7d                             # auto-expire preview in 7 days

  cleanup_preview:
    # Delete the preview when the PR is closed (merged or closed)
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SARVTEK_NICHE_FINDER }}
          projectId: sarvtek-niche-finder
          channelId: pr-${{ github.event.number }}
          expires: 1s     # effectively deletes the channel
